### ISSUE TITLE
Tab width is not applied in the second row and beyond

### ISSUE THREAD

**Issue by FerryA1** [onemen/TabMixPlus#337]
I have set tab width to a fixed one, 128, it makes easier to close several tab in a row pressing the X button one after another without moving the mouse. Max rows to be shown are set to 3.

If I open new, blank tabs (same happens with links) in the first row, tabs respect the width I set.

![](https://github.com/user-attachments/assets/47f9d540-2a41-4e53-bd68-ed4ee23e43f1)

Once the first row is filled, the next tab opens in the second tab, but width is not the one I set, but much wider.

![](https://github.com/user-attachments/assets/9e41c513-8e22-48b2-9722-e27035ef39ac)

If I fill second row with tabs, their width gets reduced until they match the correct width, the one I set. In the next row, third one, will happen the same…

![](https://github.com/user-attachments/assets/43a2f974-e14e-4e31-9172-ce22a152ae05)

This is with TMP 1.24.0 (updated today) and FF v 115.11ESR (macOS Mojave)

**Comment by FerryA1** [comment]
Hmmm… Me again. Just noticed that tab size in first row, although small, is not the one I set, 128, but 143-144. BTW, "Tab width fits to tab title" is disabled.  
  
Also, I tried to to uninstall and reinstall, with restarts between both, v1.24.0, to no avail. Reverting to v1.23.0 fixes the issue.

**Comment by onemen** [comment]
Post your Tab Mix preference.

In the last version i have change how tab width is calculated when `"Tab width fits to tab title" is disabled.` is order to fill the entire row with tab. bat tab width in the 2nd row should be fixed to minimum width.

I will have to test how i work with your setting to see if there is something wrong in the logic

**Comment by onemen** [comment]
@FerryA1,

Regarding changing the tab width to fix the window width, let me know if this automatic width change is bothering you.

As for the issue of tab width in the 2nd row, I suspect that the changes I have made to the styles applys only on Windows.
I will try this weekend to update my virtual machine (`Oracle VirtualBox`) and test Tab Mix on macOS and Linux.

**Comment by onemen** [comment]
do you see any messages in the browser console after you start the browser

try to resize the window, does it change the with of the tabs in the 2nd row?

**Comment by FerryA1** [comment]
I'll reinstall v1.24.0 and report back.

**Comment by FerryA1** [comment]
Hmmm… First of all, no messages at browser opening. Then, I followed your steps: activated remote debugging, entered the text in the search box, but nothing is shown in the console:

![](https://github.com/user-attachments/assets/248d45e5-142d-4b68-a3a2-fd360ad39d8e)

BUT… I just noticed a difference in behaviour in this installation: I simply updated from v1.23.0 to v.1.24.0, no browser restart involved, and now tabs in the second row do not expand to fit row lenght… 🤔

![](https://github.com/user-attachments/assets/416ee2e7-d44f-47ea-aa03-97eac4c83663)

They are still longer than my settings, 143 px long instead of 128 set by me. Let me restart and see if behaviour changes…

**Comment by FerryA1** [comment]
Yes, after restarting browser, behavior coms back to the one described in my first post: first line, tabs measuring 143 px, not 128 as per my settings; second row, tabs much wider, 255 px.

Also, Console shows (without any filter) a lot more info related to TabMixPlus, not shown with v1.23.0, find it below:

```
Applying chrome://tabmixplus/content/tabmix.xhtml to chrome://browser/content/browser.xhtml Overlays.jsm:96:15
Applying chrome://tabmixplus/content/overlay/tabContextMenu.xhtml to chrome://browser/content/browser.xhtml Overlays.jsm:96:15
Loading eval'd script into chrome://browser/content/browser.xhtml Overlays.jsm:567:15
Tabmix initializer: ▶️ Object { key: "init", phase: {…} }     tabmix.js:1189:17
Tabmix initializer: ▶️ Object { key: "beforeStartup", phase: {…} }    tabmix.js:1189:17
Tabmix initializer: ▶️ Object { key: "onContentLoaded", phase: {…} }    tabmix.js:1189:17
Tabmix initializer: ▶️ Object { key: "beforeBrowserInitOnLoad", phase: {…} }    tabmix.js:1189:17
Tabmix initializer: ▶️ Object { key: "onWindowOpen", phase: {…} }    tabmix.js:1189:17
Warning: attempting to write 7948 bytes to preference browser.uiCustomization.state. This is bad for general performance and memory usage. Such an amount of data should rather be written to an external file. 

❗️Tabmix ERROR at TMP_EL_onWindowOpen:     tabmix.js:1198:18
TMP_eventListener.onWindowOpen failed
DOMLocalization.setAttributes: Argument 1 is not an object.
Stack Trace:
    File "chrome://tabmixplus/content/tabmix.js", line 571, col 21, in TMP_EL_onWindowOpen
    File "chrome://tabmixplus/content/tabmix.js", line 1193, col 29, in tabmix_initialization_run
   File "chrome://tabmixplus/content/tabmix.js", line 241, col 29, in TMP_EL_init 
Tabmix initializer: ▶️ Object { key: "afterDelayedStartup", phase: {…} }    tabmix.js:1189:17

❗️Attempt to override an existing message: "main-context-menu-strip-on-share-link". preview/stripOnShare.ftl
❗️Attempt to override an existing message: "text-action-strip-on-share". preview/stripOnShare.ftl
❗️Attempt to override an existing message: "main-context-menu-strip-on-share-link". preview/stripOnShare.ftl
❗️Attempt to override an existing message: "text-action-strip-on-share". preview/stripOnShare.ftl
❗️Attempt to override an existing message: "main-context-menu-strip-on-share-link". preview/stripOnShare.ftl
❗️Attempt to override an existing message: "text-action-strip-on-share". preview/stripOnShare.ftl
❗️Attempt to override an existing message: "main-context-menu-strip-on-share-link". preview/stripOnShare.ftl
❗️Attempt to override an existing message: "text-action-strip-on-share". preview/stripOnShare.ftl
❗️Attempt to override an existing message: "main-context-menu-strip-on-share-link". preview/stripOnShare.ftl
❗️Attempt to override an existing message: "text-action-strip-on-share". preview/stripOnShare.ftl
❗️Attempt to override an existing message: "main-context-menu-strip-on-share-link". preview/stripOnShare.ftl
❗️Attempt to override an existing message: "text-action-strip-on-share". preview/stripOnShare.ftl
❗️Attempt to override an existing message: "main-context-menu-strip-on-share-link". preview/stripOnShare.ftl
❗️Attempt to override an existing message: "text-action-strip-on-share". preview/stripOnShare.ftl

Applying chrome://tabmixplus/content/tabmix.xhtml to chrome://browser/content/browser.xhtml 3️⃣ Overlays.jsm:96:15
Applying chrome://tabmixplus/content/overlay/tabContextMenu.xhtml to chrome://browser/content/browser.xhtml Overlays.jsm:96:15
Loading eval'd script into chrome://browser/content/browser.xhtml Overlays.jsm:567:15
Tabmix initializer: ▶️ Object { key: "init", phase: {…} }    tabmix.js:1189:17
Tabmix initializer: ▶️ Object { key: "beforeStartup", phase: {…} }    tabmix.js:1189:17
Tabmix initializer: ▶️ Object { key: "onContentLoaded", phase: {…} }    tabmix.js:1189:17
Tabmix initializer: ▶️ Object { key: "beforeBrowserInitOnLoad", phase: {…} }    tabmix.js:1189:17
Tabmix initializer: ▶️ Object { key: "onWindowOpen", phase: {…} }    tabmix.js:1189:17

❗️Tabmix ERROR at TMP_EL_onWindowOpen:     tabmix.js:1198:18
TMP_eventListener.onWindowOpen failed 
DOMLocalization.setAttributes: Argument 1 is not an object. 
Stack Trace: 
    File "chrome://tabmixplus/content/tabmix.js", line 571, col 21, in TMP_EL_onWindowOpen 
    File "chrome://tabmixplus/content/tabmix.js", line 1193, col 29, in tabmix_initialization_run 
    File "chrome://tabmixplus/content/tabmix.js", line 241, col 29, in TMP_EL_init 

Tabmix initializer: ▶️ Object { key: "afterDelayedStartup", phase: {…} }   tabmix.js:1189:17
Applying chrome://tabmixplus/content/overlay/tabContextMenu.xhtml to chrome://browser/content/browser.xhtml Overlays.jsm:96:15
Loading eval'd script into chrome://browser/content/browser.xhtml    Overlays.jsm:567:15
Tabmix initializer: ▶️ Object { key: "init", phase: {…} }    tabmix.js:1189:17
Tabmix initializer: ▶️ Object { key: "beforeStartup", phase: {…} }    tabmix.js:1189:17
Tabmix initializer: ▶️ Object { key: "onContentLoaded", phase: {…} }    tabmix.js:1189:17
Tabmix initializer: ▶️ Object { key: "beforeBrowserInitOnLoad", phase: {…} }    tabmix.js:1189:17
Tabmix initializer: ▶️ Object { key: "onWindowOpen", phase: {…} }    tabmix.js:1189:17

❗️Tabmix ERROR at TMP_EL_onWindowOpen:    tabmix.js:1198:18
TMP_eventListener.onWindowOpen failed 
DOMLocalization.setAttributes: Argument 1 is not an object. 
Stack Trace: 
    File "chrome://tabmixplus/content/tabmix.js", line 571, col 21, in TMP_EL_onWindowOpen 
    File "chrome://tabmixplus/content/tabmix.js", line 1193, col 29, in tabmix_initialization_run 
    File "chrome://tabmixplus/content/tabmix.js", line 241, col 29, in TMP_EL_init 

Tabmix initializer: ▶️ Object { key: "afterDelayedStartup", phase: {…} }    tabmix.js:1189:17

❗️Attempt to override an existing message: "main-context-menu-strip-on-share-link". preview/stripOnShare.ftl
❗️Attempt to override an existing message: "text-action-strip-on-share". preview/stripOnShare.ftl

Applying chrome://tabmixplus/content/overlay/tabContextMenu.xhtml to chrome://browser/content/browser.xhtml Overlays.jsm:96:15
Loading eval'd script into chrome://browser/content/browser.xhtml Overlays.jsm:567:15
Tabmix initializer: ▶️ Object { key: "init", phase: {…} }    tabmix.js:1189:17
```

**Comment by onemen** [comment]
Thank you for this info.

- first, try to clear cache, 
  Open about:support page and click "Clear startup cache…" to force Firefox to load the installed scripts and extensions on the next startup.

- From the output above it is clear that there is some issue when Tab mix start, when it try to load some localized strings.
what language your Firefox using? post the value from `about:config` -> `intl.accept_languages`
![console output](https://github.com/user-attachments/assets/48edf1a1-1552-4b8d-9a35-14da6451854b)

- I gave you the wrong preference to enter command into the `Browser console`, the correct preference is to set `devtools.chrome.enabled` to `true`. then reopen the `Browser Console` it should look like this
![console image](https://github.com/user-attachments/assets/6632ee9c-e449-4397-b967-0df84a6ef111)
now when you enter `Tabmix.tabsUtils._overflow_max_width` into the command line and press enter, If the value is above 250 then it indication that Tab mix did not start properly. I will update the code so the default value will be the current `min-width`

- You are using **old** version of Firefox ESR. consider installing [Firefox ESR 128](https://www.mozilla.org/en-US/firefox/all/desktop-esr/)

- If you are upgrading to Firefox 128, you should also reinstall [Firefox Scripts](https://github.com/xiaoxiaoflood/firefox-scripts)

- if you are still see the above error when Firefox starts even with new Firefox version, consider creating new profile

**Comment by FerryA1** [comment]
My Firefox browser is the Spanish localized one:  
  
`intl.accept_languages` = `es-ES, es, en-US, en`

The value you asked for from the Console:

`Tabmix.tabsUtils._overflow_max_width` = `137.6`

Yes, my version of FF is v115.11.0esr. As for upgrading to a newer version, some useful add-ons would stop working, so……… I'll take a look, anyway.

Now, the news:

\-After clearing the caches and restarting, second row tabs are the same size as first row ones.  
\-Now I noticed how it works: tabs not filling the first row are set to 133px. When no more tabs can be fitted in the row, all tabs in this row will be width-expanded -to 143px in my case, ten tabs per row- in order to fill the whole row, no unused space left. Not bad, but this is not respecting my setting, 128px (one more tab per row), so maybe a new preferences switch should be set.  
\-New Console TMP-related output:

```
Applying chrome://tabmixplus/content/tabmix.xhtml to chrome://browser/content/browser.xhtml Overlays.jsm:96:15
Applying chrome://tabmixplus/content/overlay/tabContextMenu.xhtml to chrome://browser/content/browser.xhtml Overlays.jsm:96:15
Loading eval'd script into chrome://browser/content/browser.xhtml Overlays.jsm:567:15
Tabmix initializer: ▶️ Object { key: "init", phase: {…} }    tabmix.js:1197:17
Tabmix initializer: ▶️ Object { key: "beforeStartup", phase: {…} }    tabmix.js:1197:17
Tabmix initializer: ▶️ Object { key: "onContentLoaded", phase: {…} }    tabmix.js:1197:17
Tabmix initializer: ▶️ Object { key: "beforeBrowserInitOnLoad", phase: {…} }    tabmix.js:1197:17
Tabmix initializer: ▶️ Object { key: "onWindowOpen", phase: {…} }    tabmix.js:1197:17
Warning: attempting to write 7948 bytes to preference browser.uiCustomization.state. This is bad for general performance and memory usage. Such an amount of data should rather be written to an external file.

❗️Tabmix:
    change_tabContainer was unable to change TabBarVisibility.update.
    can't find string
         if (nonPopupWithVerticalTabs) {
    Try Tabmix latest development version from https://bitbucket.org/onemen/tabmixplus-for-firefox/downloads/,
    Report about this to Tabmix developer at https://github.com/onemen/TabMixPlus/issues changecode.js:170:17

Tabmix initializer: ▶️ Object { key: "afterDelayedStartup", phase: {…} }    tabmix.js:1197:17

❗️Attempt to override an existing message: "main-context-menu-strip-on-share-link". preview/stripOnShare.ftl
❗️Attempt to override an existing message: "text-action-strip-on-share". preview/stripOnShare.ftl
❗️Attempt to override an existing message: "main-context-menu-strip-on-share-link". preview/stripOnShare.ftl
❗️Attempt to override an existing message: "text-action-strip-on-share". preview/stripOnShare.ftl
❗️Attempt to override an existing message: "main-context-menu-strip-on-share-link". preview/stripOnShare.ftl
❗️Attempt to override an existing message: "text-action-strip-on-share". preview/stripOnShare.ftl
❗️Attempt to override an existing message: "main-context-menu-strip-on-share-link". preview/stripOnShare.ftl
❗️Attempt to override an existing message: "text-action-strip-on-share". preview/stripOnShare.ftl
❗️Attempt to override an existing message: "main-context-menu-strip-on-share-link". preview/stripOnShare.ftl
❗️Attempt to override an existing message: "text-action-strip-on-share". preview/stripOnShare.ftl

Applying chrome://tabmixplus/content/tabmix.xhtml to chrome://browser/content/browser.xhtml 2 Overlays.jsm:96:15
Applying chrome://tabmixplus/content/overlay/tabContextMenu.xhtml to chrome://browser/content/browser.xhtml Overlays.jsm:96:15
Loading eval'd script into chrome://browser/content/browser.xhtml Overlays.jsm:567:15
Tabmix initializer: ▶️ Object { key: "init", phase: {…} }    tabmix.js:1197:17
Tabmix initializer: ▶️ Object { key: "beforeStartup", phase: {…} }    tabmix.js:1197:17
Tabmix initializer: ▶️ Object { key: "onContentLoaded", phase: {…} }    tabmix.js:1197:17
Tabmix initializer: ▶️ Object { key: "beforeBrowserInitOnLoad", phase: {…} }    tabmix.js:1197:17
Tabmix initializer: ▶️ Object { key: "onWindowOpen", phase: {…} }    tabmix.js:1197:17

❗️Tabmix:
    change_tabContainer was unable to change TabBarVisibility.update.    changecode.js:170:17
    can't find string
         if (nonPopupWithVerticalTabs) {
    Try Tabmix latest development version from https://bitbucket.org/onemen/tabmixplus-for-firefox/downloads/,
    Report about this to Tabmix developer at https://github.com/onemen/TabMixPlus/issues
 
Tabmix initializer: ▶️ Object { key: "afterDelayedStartup", phase: {…} }    tabmix.js:1197:17
Applying chrome://tabmixplus/content/overlay/tabContextMenu.xhtml to chrome://browser/content/browser.xhtml Overlays.jsm:96:15
Loading eval'd script into chrome://browser/content/browser.xhtml Overlays.jsm:567:15
Tabmix initializer: ▶️ Object { key: "init", phase: {…} }    tabmix.js:1197:17
Tabmix initializer: ▶️ Object { key: "beforeStartup", phase: {…} }    tabmix.js:1197:17
Tabmix initializer: ▶️ Object { key: "onContentLoaded", phase: {…} }    tabmix.js:1197:17
Tabmix initializer: ▶️ Object { key: "beforeBrowserInitOnLoad", phase: {…} }    tabmix.js:1197:17
Tabmix initializer: ▶️ Object { key: "onWindowOpen", phase: {…} }    tabmix.js:1197:17

❗️Tabmix:
    change_tabContainer was unable to change TabBarVisibility.update.    changecode.js:170:17
    can't find string
         if (nonPopupWithVerticalTabs) {
    Try Tabmix latest development version from https://bitbucket.org/onemen/tabmixplus-for-firefox/downloads/,
    Report about this to Tabmix developer at https://github.com/onemen/TabMixPlus/issues

Tabmix initializer: ▶️ Object { key: "afterDelayedStartup", phase: {…} }    tabmix.js:1197:17
```

**Comment by onemen** [comment]
this error already fixed in the latest development build
```
❗️Tabmix:
    change_tabContainer was unable to change TabBarVisibility.update.
    can't find string
         if (nonPopupWithVerticalTabs) {
    Try Tabmix latest development version from https://bitbucket.org/onemen/tabmixplus-for-firefox/downloads/,
    Report about this to Tabmix developer at https://github.com/onemen/TabMixPlus/issues changecode.js:170:17
```

Tab mix just add the extra apace to make the tab fill the row when it is in multi-row, there are no space for one more tab in your stings. the total width of 143px includes 2px padding on both side. if you want extra tab in each row try to reduce min-width by a few pixels.

**Comment by FerryA1** [comment]
Thanks a lot. Reducing tab width to 124px, both min and max, does the job. It is a change in the behaviour of the add-on compared to v1.23.0, so please consider mentioning it in the change log.  
  
Again, thanks a lot for your help. Since there is no bug, just a change in behaviour, I close the report.
